// app/api/webhooks/stripe/route.ts
import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { Stripe } from "stripe";
import { prisma } from "@/lib/db";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: "2024-12-18.acacia",
});

const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET!;

export async function POST(req: Request) {
  const body = await req.text();
  const headerList = await headers();
  const signature = headerList.get("stripe-signature");

  if (!signature) {
    return new NextResponse("Missing signature", { status: 400 });
  }

  let event: Stripe.Event;

  // 1. Verify the event came from Stripe (Security)
  try {
    event = stripe.webhooks.constructEvent(body, signature, webhookSecret);
  } catch (error) {
    console.error("Webhook verification failed:", error);
    return new NextResponse("Webhook error", { status: 400 });
  }

  // 2. Handle the "Checkout Completed" event
  if (event.type === "checkout.session.completed") {
    const session = event.data.object as Stripe.Checkout.Session;

    // Extract metadata we sent earlier
    const userId = session.metadata?.userId;
    const ticketVariantId = session.metadata?.ticketVariantId;
    const email = session.customer_details?.email;
    const amountTotal = session.amount_total ? session.amount_total / 100 : 0; // Convert from cents

    if (!userId || !ticketVariantId) {
      console.error("Missing metadata in Stripe session");
      return new NextResponse("Metadata missing", { status: 400 });
    }

    try {
      // 3. DATABASE TRANSACTION: Ensure all or nothing
      // We create the Order, Create the Ticket, and Reduce Stock together
      await prisma.$transaction(async (tx) => {
        // A. Create Order
        const order = await tx.order.create({
          data: {
            userId: userId,
            status: "PAID",
            totalAmount: amountTotal,
            stripePaymentId: session.id,
          },
        });

        // B. Create Ticket
        await tx.ticket.create({
          data: {
            orderId: order.id,
            ticketVariantId: ticketVariantId,
            eventId: session.metadata!.eventId, // We also need this in metadata!
            status: "VALID",
            // qrCodeToken is auto-generated by default(uuid) in schema
          },
        });

        // C. Update Stock
        await tx.ticketVariant.update({
          where: { id: ticketVariantId },
          data: {
            // atomic decrement prevents race conditions
            // (e.g. 2 people buying the last ticket at same time)
            totalStock: { decrement: 1 },
          },
        });
      });

      console.log(`✅ Success: Ticket created for user ${userId}`);
    } catch (error) {
      console.error("Database Transaction Failed:", error);
      return new NextResponse("Database error", { status: 500 });
    }
  }

  return new NextResponse("Received", { status: 200 });
}
